backend:
  name: github
  repo: miguelvargasvalencia/tutoring-blog   # ← change if your repo slug differs
  branch: main
  app_id: Ov23limXNxz1yenS6kOV
  auth_endpoint: https://decap-oauth.netlify.app/auth


media_folder: "public/assets/images"
public_folder: "/assets/images"

collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "_posts"
    format: "frontmatter"
    create: true
    fields:
      - { name: title, label: Title }
      - { name: excerpt, label: Excerpt }
      - { name: coverImage, label: Cover Image, widget: image }
      - { name: body, label: Body, widget: markdown }
